global:
  runner: 
    containers:
    - image: razorci/golang:1.14
      environment:
      - DB_CONNECTION=mongodb://appuser:apppass@localhost:27017/test
      - DB_NAME=test
    - image: bitnami/mongodb:4.4.1
      environment:
      - MONGODB_ROOT_PASSWORD=adminpass
      - MONGODB_DATABASE=test
      - MONGODB_USERNAME=appuser
      - MONGODB_PASSWORD=apppass
tasks:
  test:
    steps:
    - checkout
    - commands:
      - |
        cd server
        go mod download
        go test ./...
