services:
  api:
    build:
      context: server/
      target: build
    depends_on:
      - db
    environment:
      DB_CONNECTION: mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:27017/${DB_NAME}
      DB_NAME: ${DB_NAME}
    image: todo/go-to-do-api:rc
    command:
    - sh
    - -c
    - "go test ./..."
  db:
    image: bitnami/mongodb:${DB_IMAGE_TAG}
    environment:
      MONGODB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MONGODB_DATABASE: ${DB_NAME}
      MONGODB_USERNAME: ${DB_USER}
      MONGODB_PASSWORD: ${DB_PASS}
